### ISSUE TITLE
Finish ToDo Functionality

### ISSUE THREAD

**Issue by joanna-tan** [joanna-tan/Mentorly#11]
- [X] Users can view a list of all ToDo items assigned to them
- [X] Users can add a new ToDo item
- [X] ToDo item is assigned a due date
- [X] Tap to expand ToDo item
